name: Build release

on:
  release:
    types: published

jobs:
  generate_cv:
    name: Generate cv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile document
        run: ./compile.sh

      - name: Upload document to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cv.pdf
          asset_name: cv_${{ github.ref_name }}.pdf
          tag: ${{ github.ref }}
          overwrite: true
